export DATABASE_NAME='flaskie_test'
export DATABASE_USER='asheuh'
export DATABASE_PASSWORD='mermaid'
export DATABASE_HOST='localhost'
export SECRET_KEY='i love hot ladies'
export ENVIRONMENT="DEVELOPMENT"
export FLASK_DEBUG = 1
export TEST_DATABASE_URI="postgres://postgres@localhost/travis_test"
export FLASK_APP='app.py'